parameters:
    database_url: 'mysql://%env(MYSQL_USER)%:%env(MYSQL_PASSWORD)%@%env(MYSQL_HOST)%/%env(MYSQL_DB_NAME)%'

doctrine:
    dbal:
        url: '%database_url%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Product:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Domain/Model/Product'
                prefix: 'App\Domain\Model\Product'
                alias: Product
            Family:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Domain/Model/Family'
                prefix: 'App\Domain\Model\Family'
                alias: Family
            User:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Domain/Model/User'
                prefix: 'App\Domain\Model\User'
                alias: User
            ProductImage:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Domain/Model/Product'
                prefix: 'App\Domain\Model\Product'
                alias: ProductImage
            Cart:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Domain/Model/Cart'
                prefix: 'App\Domain\Model\Cart'
                alias: Cart
            CartLine:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Domain/Model/Cart'
                prefix: 'App\Domain\Model\Cart'
                alias: CartLine
            Order:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Domain/Model/Order'
                prefix: 'App\Domain\Model\Order'
                alias: Order
            OrderLines:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Domain/Model/Order'
                prefix: 'App\Domain\Model\Order'
                alias: OrderLines

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
